---
- name: Install basic apps for gaming
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: paru
    name:
      - cachyos-gaming-meta
      - cachyos-gaming-applications
      - proton-cachyos-slr
