---
- name: Create aur_builder user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow aur_builder to run pacman commands without password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman, /usr/bin/makepkg"
    create: true
    mode: "0440"
    validate: "visudo -cf %s"

- name: Install basic apps
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: paru
    name:
      - samsung-unified-driver-printer
      - p7zip
      - ntfs-3g
      - calc
      - btop
